### ISSUE TITLE
One of the earlier 4 commits broke the pages for v6

### ISSUE THREAD

**Issue by sarthikg** [sequelize/sequelize.org#5]
![Screenshot 2021-10-31 at 2 31 33 PM](https://user-images.githubusercontent.com/38561148/139575425-842e3d0d-0669-469c-a792-3c3a3ecbe8a7.png)

**Comment by CyberCitizen01** [comment]
@sarthikg 
Yes same for me, and apparently current maintainers are looking into it (https://github.com/sequelize/sequelize/issues/13612#issuecomment-955635728).
Also I think https://github.com/sequelize/sequelize/issues/13612 is the place where it is getting discussed

**Comment by sushantdhiman** [comment]
Reason for documentation issue is explained [here](https://github.com/sequelize/sequelize/issues/13612#issuecomment-955635728), there is nothing wrong with commits made in this repository.

Once the `npm run docs` script works ok on the main repository, documentation will correct itself. Closing in favour of https://github.com/sequelize/sequelize/issues/13612
